#!/bin/bash

source /etc/update-motd.d/colors.txt

echo -e "${YEL}  ___            ___
 /   \\          /   \\
 \\_   \\        /  __/
  _\\   \\      /  /__    ${NC}███${RED}╗${NC}   ███${RED}╗${NC} ██████${RED}╗${NC}  ██████${RED}╗${NC} ███████${RED}╗${NC}███████${RED}╗${YEL}
  \\___  \\____/   __/    ${NC}████${RED}╗${NC} ████${RED}║${NC}██${RED}╔═══${NC}██${RED}╗${NC}██${RED}╔═══${NC}██${RED}╗${NC}██${RED}╔════╝${NC}██${RED}╔════╝${YEL}
      \\_       _/       ${NC}██${RED}╔${NC}████${RED}╔${NC}██${RED}║${NC}██${RED}║${NC}   ██${RED}║${NC}██${RED}║${NC}   ██${RED}║${NC}███████${RED}╗${NC}█████${RED}╗${YEL}
        | ${NC}@ @${YEL}  \\_       ${NC}██${RED}║╚${NC}██${RED}╔╝${NC}██${RED}║${NC}██${RED}║${NC}   ██${RED}║${NC}██${RED}║${NC}   ██${RED}║╚════${NC}██${RED}║${NC}██${RED}╔══╝${YEL}
        |               ${NC}██${RED}║ ╚═╝ ${NC}██${RED}║╚${NC}██████${RED}╔╝╚${NC}██████${RED}╔╝${NC}███████${RED}║${NC}███████${RED}╗${YEL}
      _/     /\\         ${RED}╚═╝     ╚═╝ ╚═════╝  ╚═════╝ ╚══════╝╚══════╝${YEL}
     /o)  (o/\ \\_
     \\_____/ /
       \\____/${NC}
"
