#!/bin/bash

source /etc/update-motd.d/colors.txt

declare -a services=(
"cron"
"systemd-timesyncd"
"nginx"
"postgresql"
"redis-server"
"grafana-agent"
"minecraft"
)

declare -a serviceName=(
"CRON"
"NTP"
"Nginx"
"PostgreSQL"
"Redis"
"Grafana"
"Minecraft"
)

declare -a serviceStatus=()

# Get service status
for service in "${services[@]}"
do
    serviceStatus+=($(systemctl is-active "$service.service"))
done

# Max column width
width=$((64-2))

line=" Service Status......: "

for i in ${!serviceStatus[@]}
do
    # Next line and next line length
    next=" ${serviceName[$i]}: \e[5m${serviceStatus[$i]}"
    nextLen=$((1+${#next}))

    # If the current line will exceed the max column with then echo the current line and start a new line
    if [[ $((lineLen+nextLen)) -gt width ]]; then
	echo -e "$line"
	lineLen=0
	line="                       "
    fi

    lineLen=$((lineLen+nextLen))

    # Color the next line green if it's active, else red
    if [[ "${serviceStatus[$i]}" == "active" ]]; then
	line+="\e[32m\e[0m${serviceName[$i]}: \e[32m● ${serviceStatus[$i]}\e[0m "
    else
	line+="${serviceName[$i]}: \e[31m▲ ${serviceStatus[$i]}\e[0m "
    fi
done

# echo what is left
echo -e "$line"
